// <auto-generated />
using ApiSqlAsp.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSqlAsp.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    [Migration("20221212135608_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiSqlAsp.Models.Carros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoDeVendaId")
                        .HasColumnType("INT")
                        .HasColumnName("EstadoDeVendaId");

                    b.Property<int>("ModeloId")
                        .HasColumnType("INT")
                        .HasColumnName("ModeloId");

                    b.Property<decimal>("Valor")
                        .HasColumnType("MONEY")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("EstadoDeVendaId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Carros", (string)null);
                });

            modelBuilder.Entity("ApiSqlAsp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<int>("Telefone")
                        .HasColumnType("INT")
                        .HasColumnName("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("ApiSqlAsp.Models.EstadoDeVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("INT")
                        .HasColumnName("ClienteId");

                    b.Property<bool>("Vendido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("Vendido");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("EstadoDeVenda", (string)null);
                });

            modelBuilder.Entity("ApiSqlAsp.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("INT")
                        .HasColumnName("Ano");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Cor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Modelo", (string)null);
                });

            modelBuilder.Entity("ApiSqlAsp.Models.Carros", b =>
                {
                    b.HasOne("ApiSqlAsp.Models.EstadoDeVenda", "EstadoDeVenda")
                        .WithMany()
                        .HasForeignKey("EstadoDeVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSqlAsp.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoDeVenda");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("ApiSqlAsp.Models.EstadoDeVenda", b =>
                {
                    b.HasOne("ApiSqlAsp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
